server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
spring:
  datasource:
    url: jdbc:mysql://39.107.126.161:3306/lingyun?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useAffectedRows=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=true
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  security:
    user:
      name: admin
      password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
# Mybatis配置
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/lingyun/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lingyun.domain.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
security:
  header: authtication
  token:
    head: bears
logging:
  level:
    com.lingyun.dao: debug
